model = "gpt-5.5"
model_reasoning_effort = "medium"
personality = "pragmatic"
notify = [ "/Users/guhan/.codex/plugins/cache/openai-bundled/computer-use/1.0.770/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended" ]

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"

[mcp_servers.context7.http_headers]
CONTEXT7_API_KEY = "REDACTED"

[mcp_servers.fff]
command = "fff-mcp"

[mcp_servers.apple-docs]
command = "npx"
args = [ "-y", "@kimsungwhee/apple-docs-mcp@latest" ]

[mcp_servers.ifallow]
command = "/Users/Guhan/.local/bin/ifallow"
args = [ "serve", "--mcp" ]

[mcp_servers.idesign]
command = "/Users/guhan/.local/bin/idesign-server"
enabled = false

[mcp_servers.pencil]
command = "/Users/guhan/.pencil/mcp/antigravity/out/mcp-server-darwin-arm64"
args = [ "--app", "antigravity" ]

[tui.model_availability_nux]
"gpt-5.5" = 4

[marketplaces.openai-bundled]
last_updated = "2026-05-10T14:18:11Z"
source_type = "local"
source = "/Users/guhan/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-05-07T05:17:29Z"
source_type = "local"
source = "/Users/guhan/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."build-ios-apps@openai-curated"]
enabled = true

[plugins."build-macos-apps@openai-curated"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[plugins."remotion@openai-curated"]
enabled = true

[plugins."figma@openai-curated"]
enabled = true

[plugins."canva@openai-curated"]
enabled = true

[plugins."browser-use@openai-bundled"]
enabled = true

[apps.asdk_app_698f531bfb808191933a0dedad26a8c7]
enabled = false

[features]
terminal_resize_reflow = true
prevent_idle_sleep = true

[agents]
max_threads = 8
